#!/bin/sh

# scripts/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -ev

cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  brew bundle check >/dev/null 2>&1  || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }
fi

hash swiftlint 2>/dev/null  || {
  echo "==> Installing swiftlint…"
  brew install swiftlint
}
hash xcodegen 2>/dev/null  || {
  echo "==> Installing xcodegen…"
  brew install xcodegen
}
