#!/bin/sh

# scripts/build: Build the application.s

set -ev

cd "$(dirname "$0")/.."

[ -z "$DEBUG" ] || set -x

echo "==> Building…"

BUILD_TYPE=$(echo ${1-release} | tr '[:upper:]' '[:lower:]')
swift build -c ${BUILD_TYPE}
