#!/bin/sh

# scripts/test: Run test suite for application. Optionally pass in a path to an
#              individual test file to run a single test.

set -ev

cd "$(dirname "$0")/.."

[ -z "$DEBUG" ] || set -x

echo "==> Running tests…"

swift test --enable-code-coverage

# Export coverage report for codecov.io
llvm-cov show .build/x86_64-apple-macosx/debug/BundleKitPackageTests.xctest/Contents/MacOS/BundleKitPackageTests \
  -instr-profile=.build/x86_64-apple-macosx/debug/codecov/default.profdata  > coverage.txt
